# Generated by Django 5.2.3 on 2025-07-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin', models.TextField()),
                ('type', models.CharField(choices=[('justificatif', 'Justificatif'), ('pdf_final', 'PDF Final')], max_length=20)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='demandes.demande')),
            ],
        ),
    ]
