# Generated by Django 5.2.3 on 2025-07-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('hopital', 'Hôpital'), ('ecole', 'École'), ('marche', 'Marché'), ('autre', 'Autre')], max_length=20)),
                ('quartier', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communes.commune')),
            ],
        ),
    ]
