# Generated by Django 5.0.1 on 2025-08-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_centreinteret_latitude_centreinteret_longitude'),
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreinteret',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communes.quartier'),
        ),
    ]
