# Generated by Django 5.2.3 on 2025-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecerequise',
            name='obligatoire',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='piecerequise',
            unique_together={('document', 'libelle_piece', 'commune')},
        ),
    ]
