# Generated by Django 5.2.3 on 2025-07-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='quartier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communes.quartier'),
            preserve_default=False,
        ),
    ]
