# Generated by Django 5.0.1 on 2025-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_demande_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='rejet_par',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('operateur', 'Opérateur')], max_length=20, null=True),
        ),
    ]
