# Generated by Django 5.0.1 on 2025-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_demande_rejet_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='fichier_confirmation',
            field=models.FileField(blank=True, null=True, upload_to='confirmations/'),
        ),
    ]
