# Generated by Django 5.2.3 on 2025-07-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur métier'), ('agent', 'Agent'), ('operateur', 'Opérateur'), ('citoyen', 'Citoyen')], default='agent', max_length=20),
        ),
    ]
