# Generated by Django 5.2.3 on 2025-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_customuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_verification',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
    ]
