# Generated by Django 5.2.3 on 2025-07-21 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevée'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('document', 'Document'), ('system', 'Système')], default='info', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'lu'], name='notificatio_user_id_cf0127_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'archive'], name='notificatio_user_id_146d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['date_creation'], name='notificatio_date_cr_1b0271_idx'),
        ),
    ]
